name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Set environment variables
      run: |
        echo "NODE_ENV=production" >> $GITHUB_ENV
        echo "VITE_REACT_APP_BASE_URL_PROD=https://your-production-api-url.com" >> $GITHUB_ENV

    - name: Install dependencies
      run: npm ci

    - name: Build the project
      run: npm run build --if-present
