name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted  # Run on a self-hosted runner

    strategy:
      matrix:
        node-version: [20.x]  # Use Node.js version 20.x

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Checkout the repository

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}  # Use the Node.js version from the matrix
        cache: 'npm'  # Cache npm dependencies to speed up subsequent builds

    - name: Install dependencies
      run: npm install  # Install the project dependencies

    - name: Set environment variables
      run: |
        echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> $GITHUB_ENV 
        echo "VITE_REACT_APP_BASE_URL_PROD=${{ secrets.VITE_REACT_APP_BASE_URL_PROD }}" >> $GITHUB_ENV 

    - name: Build the project
      run: npm run build  # Build the project
